Start time: 08:57
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/attr_sel_1_100000_dist.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/qrangesel_2000_1_100000_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/sif_gt_sel_2000_1_100000_in_dist_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 40
distribution: sel_1_100000_dist
collection name: collection_hnsw_deep10m_sel_1_100000_dist_efc1000
mode: construction
d: 96
Failed to create new connection using: 100428ea36f94ceb869a3d46244cb04a
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/attr_sel_1_100000_dist.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/qrangesel_2000_1_100000_in_dist.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_dist/sif_gt_sel_2000_1_100000_in_dist_10.json 10 40 1000 40 sel_1_100000_dist collection_hnsw_deep10m_sel_1_100000_dist_efc1000 construction 96"
	User time (seconds): 13.37
	System time (seconds): 0.08
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18391
	Voluntary context switches: 1930
	Involuntary context switches: 154
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
