Start time: 09:02
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 46f772e3eef74aaf98dcce89e381b8bb
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.33
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18406
	Voluntary context switches: 1912
	Involuntary context switches: 141
	Swaps: 0
	File system inputs: 16
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:07
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 8dd45abc923a4cdd905b7f9a442885f5
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.32
	System time (seconds): 0.17
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18410
	Voluntary context switches: 1949
	Involuntary context switches: 174
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 9948ce2ad57c4ed598857fa36677eff7
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.31
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18414
	Voluntary context switches: 1950
	Involuntary context switches: 150
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:17
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: bccfd58bf3304a738add3264592513d8
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.39
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18413
	Voluntary context switches: 1928
	Involuntary context switches: 117
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:23
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 9ac7460816b44e0f8e743ba5c1d66a30
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.37
	System time (seconds): 0.11
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18415
	Voluntary context switches: 1937
	Involuntary context switches: 94
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:27
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 4abee69910834dca80c701b071e13222
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.34
	System time (seconds): 0.13
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18410
	Voluntary context switches: 1937
	Involuntary context switches: 144
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:33
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 4dabad996a5c475a81772976d6995aaa
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.29
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18415
	Voluntary context switches: 1978
	Involuntary context switches: 319
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:39
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: c344e9937b504a66b66ad04088f94d03
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.41
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18411
	Voluntary context switches: 1941
	Involuntary context switches: 101
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:44
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: b1013f4d213749a98d183fc3212a398f
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.39
	System time (seconds): 0.08
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18397
	Voluntary context switches: 1934
	Involuntary context switches: 119
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 17:27
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_random
collection name: collection_hnsw_sift1M_sel_1_2_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 55f7ccc62d294fb2b59f0f446144f3d2
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 40 1000 400 sel_1_2_random collection_hnsw_sift1M_sel_1_2_random_efc1000 construction 128"
	User time (seconds): 13.23
	System time (seconds): 0.16
	Percent of CPU this job got: 128%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18408
	Voluntary context switches: 1956
	Involuntary context switches: 428
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:01
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_in_dist
collection name: collection_hnsw_sift1M_sel_1_2_in_dist_efc1000
mode: construction
d: 128
Failed to create new connection using: 27d2b0c1f6594747a0ca38415e889024
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 40 1000 400 sel_1_2_in_dist collection_hnsw_sift1M_sel_1_2_in_dist_efc1000 construction 128"
	User time (seconds): 13.03
	System time (seconds): 0.14
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18385
	Voluntary context switches: 1853
	Involuntary context switches: 355
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:08
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_in_dist
collection name: collection_hnsw_sift1M_sel_1_2_in_dist_efc1000
mode: construction
d: 128
Failed to create new connection using: 3a380b6bc92d4285a7c2fd6f633e4e8a
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 40 1000 400 sel_1_2_in_dist collection_hnsw_sift1M_sel_1_2_in_dist_efc1000 construction 128"
	User time (seconds): 13.08
	System time (seconds): 0.14
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.44
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18410
	Voluntary context switches: 1862
	Involuntary context switches: 286
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:12
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_in_dist
collection name: collection_hnsw_sift1M_sel_1_2_in_dist_efc1000
mode: construction
d: 128
Failed to create new connection using: c35fdaadad034d2ea9d678ac00d9651f
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 40 1000 400 sel_1_2_in_dist collection_hnsw_sift1M_sel_1_2_in_dist_efc1000 construction 128"
	User time (seconds): 13.00
	System time (seconds): 0.18
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18409
	Voluntary context switches: 1921
	Involuntary context switches: 302
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:20
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_2_in_dist
collection name: collection_hnsw_sift1M_sel_1_2_in_dist_efc1000
mode: construction
d: 128
Failed to create new connection using: 0d15d27c83e4402594151d33884fb68d
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 40 1000 400 sel_1_2_in_dist collection_hnsw_sift1M_sel_1_2_in_dist_efc1000 construction 128"
	User time (seconds): 13.04
	System time (seconds): 0.14
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18419
	Voluntary context switches: 1936
	Involuntary context switches: 304
	Swaps: 0
	File system inputs: 0
	File system outputs: 24
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 20:17
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/attr_sel_1_5_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/qrangesel_1_1_5_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/sif_gt_sel_1_1_5_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_5_random
collection name: collection_hnsw_sift1M_sel_1_5_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 893f4dfc482940ffbab90157b1cda7d3
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/attr_sel_1_5_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/qrangesel_1_1_5_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/sif_gt_sel_1_1_5_random_10.json 10 40 1000 400 sel_1_5_random collection_hnsw_sift1M_sel_1_5_random_efc1000 construction 128"
	User time (seconds): 13.06
	System time (seconds): 0.08
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18416
	Voluntary context switches: 1958
	Involuntary context switches: 444
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 22:25
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: ed1ac79f4f3245c6ab34cf6c34033c65
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.08
	System time (seconds): 0.08
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18406
	Voluntary context switches: 1938
	Involuntary context switches: 330
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 02:35
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: a9030757d5af4e3ab83ab4c851327a0b
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.38
	System time (seconds): 0.11
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18424
	Voluntary context switches: 1947
	Involuntary context switches: 99
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 03:33
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 1940f756257a4104a52df747993211fb
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.13
	System time (seconds): 0.16
	Percent of CPU this job got: 127%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18408
	Voluntary context switches: 1923
	Involuntary context switches: 794
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 05:05
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 7306e225ecd846d499dc8ecc08af688d
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.11
	System time (seconds): 0.15
	Percent of CPU this job got: 127%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18421
	Voluntary context switches: 1938
	Involuntary context switches: 403
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 06:39
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: c187c19a40494863a743603b0df96400
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.36
	System time (seconds): 0.12
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18451
	Voluntary context switches: 1945
	Involuntary context switches: 232
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
