Start time: 19:23
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_1000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_1000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 232c1a001f43472cb5a697d45e777209
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_1000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_1000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.46
	System time (seconds): 0.10
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18381
	Voluntary context switches: 1928
	Involuntary context switches: 142
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 20:53
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_2000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_2000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 633eddc95345409abc8c63b748addfec
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_2000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_2000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.44
	System time (seconds): 0.13
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18363
	Voluntary context switches: 1906
	Involuntary context switches: 184
	Swaps: 0
	File system inputs: 0
	File system outputs: 24
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 22:12
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_3000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_3000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 2be0cba6e3d14f46a59d130765b3791a
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_3000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_3000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.43
	System time (seconds): 0.13
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18371
	Voluntary context switches: 1950
	Involuntary context switches: 125
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 23:41
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_4000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_4000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 4406ee315bf4416f8347d0b3faebc4e3
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_4000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_4000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.40
	System time (seconds): 0.16
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18389
	Voluntary context switches: 1952
	Involuntary context switches: 175
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 01:44
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_5000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_5000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 9c5ae49bc9974d549b7af985f7826411
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_5000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_5000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.49
	System time (seconds): 0.08
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18368
	Voluntary context switches: 1939
	Involuntary context switches: 115
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 06:55
dataset: deep10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs
query file: /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs
attr file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json
query range file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_6000_1_100000_random.json
ground truth file: /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_6000_1_100000_random_10.json
K: 10
nprobe: 30
collection name: collection_deep10m_sel_1_100000_random
Failed to create new connection using: 845ff49801ef4b9c9822a9a7be63bd85
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py deep10m 10000000 /mnt/data/mocheng/dataset/deep10m/base.10M.fvecs /mnt/data/mocheng/dataset/deep10m/query.public.10K.fvecs /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/attr_sel_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/qrangesel_6000_1_100000_random.json /mnt/data/mocheng/dataset/deep10m/label/sel_1_100000_random/sif_gt_sel_6000_1_100000_random_10.json 10 30 collection_deep10m_sel_1_100000_random query 48 96"
	User time (seconds): 13.01
	System time (seconds): 0.11
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18380
	Voluntary context switches: 1892
	Involuntary context switches: 3428
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
