Start time: 09:02
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: ee57c42bda894a66846eb29f3f26331f
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.44
	System time (seconds): 0.18
	Percent of CPU this job got: 124%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.95
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 179
	Minor (reclaiming a frame) page faults: 18388
	Voluntary context switches: 3267
	Involuntary context switches: 870
	Swaps: 0
	File system inputs: 179384
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:07
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: 6d9dcc2137054413943a3bea1611b0e5
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.40
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18379
	Voluntary context switches: 1958
	Involuntary context switches: 245
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: e710853445e94319b6d921adeaf9e935
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.27
	System time (seconds): 0.19
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18417
	Voluntary context switches: 1990
	Involuntary context switches: 295
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:17
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: 331f977eb33d41398e7e00a1d97a3e0d
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.36
	System time (seconds): 0.13
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.44
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18414
	Voluntary context switches: 1940
	Involuntary context switches: 370
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:22
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: adf57d02bb9544caadaf4e50bf39b522
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.37
	System time (seconds): 0.11
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.45
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18403
	Voluntary context switches: 1899
	Involuntary context switches: 359
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:27
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: 4028f0566b6e4e93a287146a7e79bf9b
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.37
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.43
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18392
	Voluntary context switches: 1999
	Involuntary context switches: 230
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:33
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: cdaa6b697f0948598101015442d52a1d
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.27
	System time (seconds): 0.18
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18410
	Voluntary context switches: 1980
	Involuntary context switches: 378
	Swaps: 0
	File system inputs: 0
	File system outputs: 24
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:39
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: 9a372af40ff244a4996d9a753cc19b20
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.35
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18389
	Voluntary context switches: 1900
	Involuntary context switches: 170
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:43
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: a3b7c2cb9b2e41598f3dbaa50b139030
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.35
	System time (seconds): 0.09
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18378
	Voluntary context switches: 1939
	Involuntary context switches: 229
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 17:27
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_random
Failed to create new connection using: 6becd4d27c0443209092c3b032562dd2
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/attr_sel_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/qrangesel_1_1_2_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_random/sif_gt_sel_1_1_2_random_10.json 10 10 collection_sift1M_sel_1_2_random construction 64 128"
	User time (seconds): 13.19
	System time (seconds): 0.09
	Percent of CPU this job got: 127%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18379
	Voluntary context switches: 1931
	Involuntary context switches: 420
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:00
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_in_dist
Failed to create new connection using: 48cf8a6e4c104301b95eb5a1c6dbae7c
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 10 collection_sift1M_sel_1_2_in_dist construction 64 128"
	User time (seconds): 13.10
	System time (seconds): 0.07
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.43
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18397
	Voluntary context switches: 1952
	Involuntary context switches: 283
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:08
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_in_dist
Failed to create new connection using: e674770b597246f78bf4cbe102306a06
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 10 collection_sift1M_sel_1_2_in_dist construction 64 128"
	User time (seconds): 13.08
	System time (seconds): 0.10
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18414
	Voluntary context switches: 1977
	Involuntary context switches: 424
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_in_dist
Failed to create new connection using: df4d55bc5193475d817dc6f4c506004c
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 10 collection_sift1M_sel_1_2_in_dist construction 64 128"
	User time (seconds): 12.98
	System time (seconds): 0.19
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18380
	Voluntary context switches: 1956
	Involuntary context switches: 488
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 19:20
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_2_in_dist
Failed to create new connection using: d0035b57fa46422f882f969c8ad7e382
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/attr_sel_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/qrangesel_1_1_2_in_dist.json /mnt/data/mocheng/dataset/sift/label/sel_1_2_in_dist/sif_gt_sel_1_1_2_in_dist_10.json 10 10 collection_sift1M_sel_1_2_in_dist construction 64 128"
	User time (seconds): 13.08
	System time (seconds): 0.07
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 84992
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18395
	Voluntary context switches: 1911
	Involuntary context switches: 473
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 20:17
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/attr_sel_1_5_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/qrangesel_1_1_5_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/sif_gt_sel_1_1_5_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_5_random
Failed to create new connection using: 456ec48470a441f3804fa818b9e44fe4
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/attr_sel_1_5_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/qrangesel_1_1_5_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_5_random/sif_gt_sel_1_1_5_random_10.json 10 10 collection_sift1M_sel_1_5_random construction 64 128"
	User time (seconds): 13.07
	System time (seconds): 0.14
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.43
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18370
	Voluntary context switches: 1916
	Involuntary context switches: 295
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 22:25
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: 04167edeab864dd0bd490a6363e6ca51
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.06
	System time (seconds): 0.11
	Percent of CPU this job got: 126%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18442
	Voluntary context switches: 1920
	Involuntary context switches: 496
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 02:35
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: f5b21b5cf40f4047b30d507b2c996570
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.31
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18384
	Voluntary context switches: 1899
	Involuntary context switches: 118
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 03:33
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: ca3e041572a642f6bdeba100425863bd
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.41
	System time (seconds): 0.12
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.44
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 81920
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18380
	Voluntary context switches: 1883
	Involuntary context switches: 265
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 05:05
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: bfee6f817e2243179b46af446b0fe739
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.11
	System time (seconds): 0.19
	Percent of CPU this job got: 127%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18375
	Voluntary context switches: 1981
	Involuntary context switches: 631
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 06:39
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: 4cd3ec35713f45ad9b7c4fde2808d897
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.34
	System time (seconds): 0.15
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18375
	Voluntary context switches: 1941
	Involuntary context switches: 169
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
