Start time: 08:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: 7ad2f81903054fa4a24332913a9c5910
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.32
	System time (seconds): 0.18
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18377
	Voluntary context switches: 1956
	Involuntary context switches: 256
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:42
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: 6acbfa446f6a47ac86bb45e514aa310b
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.36
	System time (seconds): 0.08
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18381
	Voluntary context switches: 1909
	Involuntary context switches: 313
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 11:14
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: 5baa5e40f9e3436782a250936aa6724b
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.38
	System time (seconds): 0.07
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 82944
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18365
	Voluntary context switches: 1923
	Involuntary context switches: 131
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 12:45
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
nprobe: 10
collection name: collection_sift1M_sel_1_100_random
Failed to create new connection using: ebc0bb36fb8f4ceab4e32b99bfa47160
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 10 collection_sift1M_sel_1_100_random construction 64 128"
	User time (seconds): 13.34
	System time (seconds): 0.14
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18394
	Voluntary context switches: 1852
	Involuntary context switches: 277
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
